# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_img',
            field=models.ImageField(default=None, upload_to=b''),
        ),
    ]
