# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_person_person_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='First_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='person',
            name='Last_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Exam.Location'),
        ),
    ]
