# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_auto_20180905_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='First_name',
            field=models.CharField(default='chetu', max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='Last_name',
            field=models.CharField(default='parikh', max_length=250),
        ),
    ]
