# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_auto_20180905_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonDetail',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
    ]
