# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0006_auto_20180905_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='chetu', max_length=70),
            preserve_default=False,
        ),
    ]
