# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0007_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(default=None, max_length=70),
        ),
    ]
