# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-09 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0009_auto_20180905_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetail',
            name='person_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
